/* ============================================================
   EXTENDED COUNTRY ALIASES — fixes Europe/Americas on map
   Merges into the main countryAliases object in charts.js
   ============================================================ */
window.addEventListener('load', function() {
    if (typeof countryAliases === 'undefined') return;
    var extra = {
        // Western Europe
        'germany':'germany','deutschland':'germany',
        'france':'france',
        'spain':'spain','espana':'spain',
        'england':'unitedkingdom','greatbritain':'unitedkingdom',
        'scotland':'unitedkingdom','wales':'unitedkingdom',
        'northernireland':'unitedkingdom',
        'netherlands':'netherlands','holland':'netherlands',
        'italy':'italy','italia':'italy',
        'portugal':'portugal',
        'belgium':'belgium',
        'sweden':'sweden','sverige':'sweden',
        'norway':'norway','norge':'norway',
        'denmark':'denmark','danmark':'denmark',
        'finland':'finland','suomi':'finland',
        'switzerland':'switzerland','suisse':'switzerland',
        'austria':'austria','osterreich':'austria',
        'poland':'poland','polska':'poland',
        'czechrepublic':'czechrepublic','czechia':'czechrepublic',
        'hungary':'hungary','magyarorszag':'hungary',
        'romania':'romania',
        'ukraine':'ukraine',
        'greece':'greece','hellas':'greece',
        'croatia':'croatia','hrvatska':'croatia',
        'serbia':'serbia',
        'slovakia':'slovakia',
        'slovenia':'slovenia',
        'bulgaria':'bulgaria',
        'iceland':'iceland','island':'iceland',
        'ireland':'ireland','republicofireland':'ireland',
        'russia':'russia','russianfederation':'russia',
        'belarus':'belarus',
        'lithuania':'lithuania','latvia':'latvia','estonia':'estonia',
        'moldova':'moldova',
        'georgia':'georgia',
        'armenia':'armenia','azerbaijan':'azerbaijan',
        'bosniaherzegovina':'bosniaherzegovina',
        'northmacedonia':'northmacedonia','macedonia':'northmacedonia',
        'albania':'albania','kosovo':'kosovo',
        'malta':'malta','cyprus':'cyprus','luxembourg':'luxembourg',
        // Americas
        'unitedstates':'unitedstates','usa':'unitedstates',
        'canada':'canada',
        'mexico':'mexico','mejico':'mexico',
        'brazil':'brazil','brasil':'brazil',
        'argentina':'argentina',
        'colombia':'colombia',
        'chile':'chile',
        'peru':'peru',
        'venezuela':'venezuela',
        'ecuador':'ecuador',
        'uruguay':'uruguay',
        'paraguay':'paraguay',
        'bolivia':'bolivia',
        'trinidad':'trinidadandtobago','tobago':'trinidadandtobago',
        'trinidadandtobago':'trinidadandtobago',
        'jamaica':'jamaica',
        'costarica':'costarica',
        'panama':'panama',
        'guatemala':'guatemala',
        'elsalvador':'elsalvador',
        'honduras':'honduras',
        'nicaragua':'nicaragua',
        'haiti':'haiti','cuba':'cuba','dominicanrepublic':'dominicanrepublic',
        'puertorico':'puertorico',
        // Asia
        'japan':'japan','nippon':'japan',
        'southkorea':'southkorea','korea':'southkorea','republicofkorea':'southkorea',
        'china':'china','chinaPR':'china','prc':'china',
        'australia':'australia',
        'newzealand':'newzealand','aotearoa':'newzealand',
        'india':'india','indonesia':'indonesia','thailand':'thailand',
        'vietnam':'vietnam','myanmar':'myanmar',
        'philippines':'philippines','malaysia':'malaysia',
        'singapore':'singapore','taiwan':'taiwan',
        'iran':'iran','iraq':'iraq','saudiarabia':'saudiarabia',
        'jordan':'jordan','lebanon':'lebanon','syria':'syria',
        'israel':'israel','palestine':'palestine',
        'kazakhstan':'kazakhstan','uzbekistan':'uzbekistan',
        // Africa
        'nigeria':'nigeria','southafrica':'southafrica',
        'ghana':'ghana','kenya':'kenya','cameroon':'cameroon',
        'ethiopia':'ethiopia','morocco':'morocco',
        'egypt':'egypt','algeria':'algeria','tunisia':'tunisia',
        'senegal':'senegal','cotedivoire':'cotedivoire','ivorycoast':'cotedivoire',
        'tanzania':'tanzania','uganda':'uganda','zimbabwe':'zimbabwe',
        'zambia':'zambia','mozambique':'mozambique',
        'angola':'angola','namibia':'namibia',
        'libya':'libya','sudan':'sudan',
        'mali':'mali','burkina':'burkinafaso','guinea':'guinea',
        'rwanda':'rwanda','burundi':'burundi',
        // Oceania
        'papua':'papuanewguinea','papuanewguinea':'papuanewguinea',
        'fiji':'fiji','samoa':'samoa','vanuatu':'vanuatu',
        'tahiti':'tahiti'
    };
    Object.assign(countryAliases, extra);
});
